baseURL = 'https://dudamakesthings.github.io'
languageCode = 'en'
DefaultContentLanguage = "en"
title = 'Duda Makes Things!'
theme = 'anatole'

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
