[[main]]
    name = "Home"
    weight = 100
    pageRef = '/'

[[main]]
    name = "Posts"
    weight = 200
    pageRef = '/post'

[[main]]
	name = "Label"
	weight = 400
	pageRef = "/label"
	# parent = "Posts"

[[main]]
	name = "Categories"
	weight = 410
	pageRef = "/categories"
	parent = "Label"

[[main]]
	name = "Tags"
	weight = 400
	pageRef = "/tags"
	parent = "Label"

# [[main]]
# 	name = "Series"
# 	weight = 230
# 	url = "/series/"
# 	parent = "Posts"

[[main]]
    name = "Projects"
    weight = 300
    pageRef = '/projects'

[[main]]
	name = "Electric Sheep Crafts"
	weight = 310
	pageRef = "/projects/esc"
	parent = "Projects"

[[main]]
	name = "Yogini Duda"
	weight = 320
	pageRef = "/projects/yoginiduda"
	parent = "Projects"

[[main]]
    name = "About"
    weight = 500
    pageRef = '/about'