[[main]]
    name = "Início"
    weight = 100
    pageRef = '/'

[[main]]
    name = "Postagens"
    weight = 200
    pageRef = '/post'

# [[main]] ->>>>>> need verification is not working
# 	name = "Categorias"
# 	weight = 210
# 	url = "/categories"
# 	parent = "Postagens"

# [[main]]
# 	name = "Etiquetas"
# 	weight = 220
# 	url = "/etiquetas"
# 	parent = "Postagens"

[[main]]
    name = "Projetos"
    weight = 300
    pageRef = '/projetos'

[[main]]
	name = "Letras & Linha"
	weight = 310
	pageRef = "/projetos/letraselinha"
	parent = "Projetos"

[[main]]
	name = "Letróloga Artista"
	weight = 320
	pageRef = "/projetos/letrologaartista"
	parent = "Projetos"

[[main]]
	name = "Electric Sheep Crafts"
	weight = 330
	pageRef = "/projetos/esc"
	parent = "Projetos"

[[main]]
	name = "Yogini Duda"
	weight = 340
	pageRef = "/projetos/yoginiduda"
	parent = "Projetos"

[[main]]
    name = "Sobre"
    weight = 400
    pageRef = '/about'