[[main]]
    name = "Home"
    weight = 100
    pageRef = '/'

[[main]]
    name = "Posts"
    weight = 200
    pageRef = '/post'

[[main]]
	name = "Categories"
	weight = 210
	url = "/categories"
	parent = "Posts"

[[main]]
	name = "Tags"
	weight = 220
	url = "/tags"
	parent = "Posts"

[[main]]
    name = "Projects"
    weight = 300
    pageRef = '/projects'

[[main]]
	name = "Electric Sheep Crafts"
	weight = 310
	url = "/esc"
	parent = "Projects"

[[main]]
	name = "Yogini Duda"
	weight = 320
	url = "/yogini_duda"
	parent = "Projects"

[[main]]
    name = "About"
    weight = 400
    pageRef = '/about'